### PR TITLE
Add TypeScript declarations

### PR DESCRIPTION
**Pull request by dkaraush**
Hey, I see you included @types and tsconfig.json in project, but there is actually no .d.ts for your library.
I just want to share it for others next time, and thought that it would be better to put it here, rather than going through publishing into @types/ for such small .d.ts
Let me know what you think!

### CODE REVIEW

**Comment by KenanY** [comment]
Well, the types are defined in `index.js` through JSDoc/TSDoc, and then type coverage is verified through type-coverage, so I don't think we really need a `.d.ts` here since TS can pull the types from the JS source.

**Comment by dkaraush** [comment]
Oh, alright. I just did plain `npm i glicko2-lite` and my tsconfig failed to detect any declarations.

**Comment by KenanY** [comment]
Hmm might need to add something like `"allowJs": true` to your `tsconfig.json` if it isn't already there. Anyways, build is failing here.

**Review by KenanY — CHANGES_REQUESTED** [review]
Fix build failures.

**Comment by KenanY** [comment]
I fixed this up in #167 and got the types to be generated from source. Published in [v3.1.0](https://github.com/KenanY/glicko2-lite/releases/tag/3.1.0). Thank you!

**Pull request closed without merging**
